export const accentColors = {
  green: {
    dark: {
      primary: '#bef264',
      primaryDim: '#a3e635',
      primaryContainer: '#cafd00',
      onPrimary: '#1a2e04',
      onPrimaryContainer: '#1a2e04',
      surfaceTint: '#bef264',
    },
    light: {
      primary: '#3f6212',
      primaryDim: '#365314',
      primaryContainer: '#bef264',
      onPrimary: '#f0ffe8',
      onPrimaryContainer: '#1a2e04',
      surfaceTint: '#3f6212',
    },
  },
  purple: {
    dark: {
      primary: '#d8b4fe',
      primaryDim: '#c084fc',
      primaryContainer: '#a855f7',
      onPrimary: '#2e1065',
      onPrimaryContainer: '#2e1065',
      surfaceTint: '#d8b4fe',
    },
    light: {
      primary: '#6b21a8',
      primaryDim: '#581c87',
      primaryContainer: '#e9d5ff',
      onPrimary: '#faf5ff',
      onPrimaryContainer: '#2e1065',
      surfaceTint: '#6b21a8',
    },
  },
  orange: {
    dark: {
      primary: '#fdba74',
      primaryDim: '#fb923c',
      primaryContainer: '#f97316',
      onPrimary: '#431407',
      onPrimaryContainer: '#431407',
      surfaceTint: '#fdba74',
    },
    light: {
      primary: '#9a3412',
      primaryDim: '#7c2d12',
      primaryContainer: '#ffedd5',
      onPrimary: '#fff7ed',
      onPrimaryContainer: '#431407',
      surfaceTint: '#9a3412',
    },
  },
};

export const darkColors = {
  surface: '#0e0e0e',
  surfaceContainerLowest: '#000000',
  surfaceContainerLow: '#141814',
  surfaceContainer: '#1c211c',
  surfaceContainerHigh: '#232823',
  surfaceContainerHighest: '#2b302b',
  surfaceBright: '#323832',
  surfaceVariant: '#2b302b',
  background: '#0e0e0e',
  onSurface: '#f0ffe8',
  onSurfaceVariant: '#b8d4b8',
  onBackground: '#f0ffe8',
  ...accentColors.green.dark,
  secondary: '#fde047',
  secondaryDim: '#facc15',
  secondaryContainer: '#713f12',
  onSecondary: '#422006',
  onSecondaryContainer: '#fef9c3',
  tertiary: '#fde047',
  tertiaryDim: '#fbbf24',
  tertiaryContainer: '#fce047',
  onTertiary: '#422006',
  onTertiaryContainer: '#1c1400',
  error: '#ff7351',
  errorDim: '#d53d18',
  errorContainer: '#b92902',
  onError: '#450900',
  onErrorContainer: '#ffd2c8',
  outline: '#6a8a6a',
  outlineVariant: '#3d5a3d',
  inverseSurface: '#f0ffe8',
  inverseOnSurface: '#1a2e04',
  inversePrimary: '#3f6212',
  gradientColors: ['#0e0e0e', '#07120a'] as string[],
};

export const lightColors = {
  surface: '#f8fdf4',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#f0faea',
  surfaceContainer: '#e5f5dc',
  surfaceContainerHigh: '#daeecf',
  surfaceContainerHighest: '#cfe6c3',
  surfaceBright: '#f8fdf4',
  surfaceVariant: '#cfe6c3',
  background: '#f8fdf4',
  onSurface: '#1a2e04',
  onSurfaceVariant: '#3a5c1a',
  onBackground: '#1a2e04',
  ...accentColors.green.light,
  secondary: '#a3e635',
  secondaryDim: '#84cc16',
  secondaryContainer: '#cafd00',
  onSecondary: '#1a2e04',
  onSecondaryContainer: '#1a2e04',
  tertiary: '#65a30d',
  tertiaryDim: '#4d7c0f',
  tertiaryContainer: '#d9f99d',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#1a2e04',
  error: '#dc2626',
  errorDim: '#b91c1c',
  errorContainer: '#fca5a5',
  onError: '#ffffff',
  onErrorContainer: '#7f1d1d',
  outline: '#4a6e1a',
  outlineVariant: '#a3c47a',
  inverseSurface: '#1a2e04',
  inverseOnSurface: '#d9f99d',
  inversePrimary: '#bef264',
  gradientColors: ['#ffffff', '#f0fde4'] as string[],
};

export type ThemeColors = typeof darkColors;

export type AccentColor = keyof typeof accentColors;

export function getColors(mode: 'dark' | 'light', accent: AccentColor): ThemeColors {
  const base = mode === 'dark' ? darkColors : lightColors;
  const accentPart = accentColors[accent][mode];
  return { ...base, ...accentPart };
}
