export const accentColors = {
  green: {
    dark: {
      primary: '#bef264',
      primaryDim: '#a3e635',
      primaryContainer: '#cafd00',
      onPrimary: '#1a2e04',
      onPrimaryContainer: '#1a2e04',
      surfaceTint: '#bef264',
      surface: '#0e0e0e',
      background: '#0e0e0e',
      surfaceContainerLow: '#141814',
      surfaceContainer: '#1c211c',
      surfaceContainerHigh: '#232823',
      surfaceContainerHighest: '#2b302b',
      outline: '#6a8a6a',
      outlineVariant: '#3d5a3d',
      onSurface: '#f0ffe8',
      onSurfaceVariant: '#b8d4b8',
    },
    light: {
      primary: '#3f6212',
      primaryDim: '#365314',
      primaryContainer: '#bef264',
      onPrimary: '#f0ffe8',
      onPrimaryContainer: '#1a2e04',
      surfaceTint: '#3f6212',
      surface: '#f8fdf4',
      background: '#f8fdf4',
      surfaceContainerLow: '#f0faea',
      surfaceContainer: '#e5f5dc',
      surfaceContainerHigh: '#daeecf',
      surfaceContainerHighest: '#cfe6c3',
      outline: '#4a6e1a',
      outlineVariant: '#a3c47a',
      onSurface: '#1a2e04',
      onSurfaceVariant: '#3a5c1a',
    },
  },
  purple: {
    dark: {
      primary: '#d8b4fe',
      primaryDim: '#c084fc',
      primaryContainer: '#a855f7',
      onPrimary: '#2e1065',
      onPrimaryContainer: '#2e1065',
      surfaceTint: '#d8b4fe',
      surface: '#0f0d14',
      background: '#0f0d14',
      surfaceContainerLow: '#1a1820',
      surfaceContainer: '#22202a',
      surfaceContainerHigh: '#2b2935',
      surfaceContainerHighest: '#33313f',
      outline: '#8b849e',
      outlineVariant: '#46425a',
      onSurface: '#f5f0ff',
      onSurfaceVariant: '#c9c3d4',
    },
    light: {
      primary: '#6b21a8',
      primaryDim: '#581c87',
      primaryContainer: '#e9d5ff',
      onPrimary: '#faf5ff',
      onPrimaryContainer: '#2e1065',
      surfaceTint: '#6b21a8',
      surface: '#fcf8ff',
      background: '#fcf8ff',
      surfaceContainerLow: '#f5f0fb',
      surfaceContainer: '#eee5f6',
      surfaceContainerHigh: '#e7daf1',
      surfaceContainerHighest: '#e0d0eb',
      outline: '#584e7a',
      outlineVariant: '#b3a7d4',
      onSurface: '#1c004d',
      onSurfaceVariant: '#4e3a73',
    },
  },
  orange: {
    dark: {
      primary: '#fdba74',
      primaryDim: '#fb923c',
      primaryContainer: '#f97316',
      onPrimary: '#431407',
      onPrimaryContainer: '#431407',
      surfaceTint: '#fdba74',
      surface: '#140f0d',
      background: '#140f0d',
      surfaceContainerLow: '#201a18',
      surfaceContainer: '#2a2220',
      surfaceContainerHigh: '#352b29',
      surfaceContainerHighest: '#3f3331',
      outline: '#9e847e',
      outlineVariant: '#5a4642',
      onSurface: '#fff0f0',
      onSurfaceVariant: '#d4c3c0',
    },
    light: {
      primary: '#9a3412',
      primaryDim: '#7c2d12',
      primaryContainer: '#ffedd5',
      onPrimary: '#fff7ed',
      onPrimaryContainer: '#431407',
      surfaceTint: '#9a3412',
      surface: '#fffaf8',
      background: '#fffaf8',
      surfaceContainerLow: '#fbf0ed',
      surfaceContainer: '#f6e5e0',
      surfaceContainerHigh: '#f1dbd5',
      surfaceContainerHighest: '#ebd0ca',
      outline: '#7a524e',
      outlineVariant: '#d4a7a3',
      onSurface: '#4d0000',
      onSurfaceVariant: '#733a36',
    },
  },
};

export const darkColors = {
  ...accentColors.green.dark,
  surfaceContainerLowest: '#000000',
  surfaceBright: '#323832',
  surfaceVariant: '#2b302b',
  onBackground: '#f0ffe8',
  secondary: '#fde047',
  secondaryDim: '#facc15',
  secondaryContainer: '#713f12',
  onSecondary: '#422006',
  onSecondaryContainer: '#fef9c3',
  tertiary: '#fde047',
  tertiaryDim: '#fbbf24',
  tertiaryContainer: '#fce047',
  onTertiary: '#422006',
  onTertiaryContainer: '#1c1400',
  error: '#ff7351',
  errorDim: '#d53d18',
  errorContainer: '#b92902',
  onError: '#450900',
  onErrorContainer: '#ffd2c8',
  inverseSurface: '#f0ffe8',
  inverseOnSurface: '#1a2e04',
  inversePrimary: '#3f6212',
};

export const lightColors = {
  ...accentColors.green.light,
  surfaceContainerLowest: '#ffffff',
  surfaceBright: '#f8fdf4',
  surfaceVariant: '#cfe6c3',
  onBackground: '#1a2e04',
  secondary: '#a3e635',
  secondaryDim: '#84cc16',
  secondaryContainer: '#cafd00',
  onSecondary: '#1a2e04',
  onSecondaryContainer: '#1a2e04',
  tertiary: '#65a30d',
  tertiaryDim: '#4d7c0f',
  tertiaryContainer: '#d9f99d',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#1a2e04',
  error: '#dc2626',
  errorDim: '#b91c1c',
  errorContainer: '#fca5a5',
  onError: '#ffffff',
  onErrorContainer: '#7f1d1d',
  inverseSurface: '#1a2e04',
  inverseOnSurface: '#d9f99d',
  inversePrimary: '#bef264',
};

export type ThemeColors = typeof darkColors;

export type AccentColor = keyof typeof accentColors;

export function getColors(mode: 'dark' | 'light', accent: AccentColor): ThemeColors {
  const base = mode === 'dark' ? darkColors : lightColors;
  const accentPart = accentColors[accent][mode];
  return { 
    ...base, 
    ...accentPart,
    onBackground: accentPart.onSurface,
    surfaceBright: accentPart.surface,
    surfaceVariant: accentPart.surfaceContainerHighest,
  };
}
